### ISSUE TITLE
ID DOC 1: Inconsistencia no Diagrama de Sequência – Solicitar bilhete

### ISSUE THREAD

**Issue by guilhermevieirasilvagoncalves** [guilhermevieirasilvagoncalves/Source-Code-Inspection#13]
Inconsistência: O método getSaldo deverá ser realizado antes do método Imprimir, uma vez que o fluxo da validação vem primeiro.

Criticidade: Alta

**Comment by Kenzo-Sugai** [comment]
Ajuste realizado alterando o diagrama de sequencia solicitar bilhete
