### ISSUE TITLE
ID DOC 2: Inconsistencia no caso de uso CSU03 – Solicitar troco (Omissão)

### ISSUE THREAD

**Issue by Kenzo-Sugai** [guilhermevieirasilvagoncalves/Source-Code-Inspection#14]
CSU03 – Solicitar troco

Omissão: Não há especificação sobre pré-condição, mas deveria estar incluído a informação de necessário papel moeda.
Criticidade: Baixo

**Comment by guilhermevieirasilvagoncalves** [comment]
Ajuste realizado, definindo uma pré condição para o CSU
