### ISSUE TITLE
ID DOC 3: Inconsistencia no caso de uso CSU03 – Solicitar troco (Ambiguidade)

### ISSUE THREAD

**Issue by Kenzo-Sugai** [guilhermevieirasilvagoncalves/Source-Code-Inspection#15]
CSU03 – Solicitar troco

Ambiguidade: Duas ações com a mesma numeração, implicando no fluxo correto do caso.
Criticidade: Baixo.

**Comment by guilhermevieirasilvagoncalves** [comment]
Realizada a correção na numeração da sequência do fluxo principal do caso.
