### ISSUE TITLE
ID 9: Erro no operador da iteração

### ISSUE THREAD

**Issue by Kenzo-Sugai** [guilhermevieirasilvagoncalves/Source-Code-Inspection#8]
O operador da iteração está errado, deveria ser --. Caso continue com ++, a variável de iteração acessará um espaço de memória inexistente no array.

Classe: TrocoIterator

Linha: 61

**Comment by guilhermevieirasilvagoncalves** [comment]
O erro já foi ajustado com o pull request Ajuste | ID 13
